# TYPE
- name: "type/bug"
  color: "d73a4a"
  description: "Something broken"
- name: "type/feature"
  color: "0e8a16"
  description: "New capability"
- name: "type/docs"
  color: "0075ca"
  description: "Documentation only"
- name: "type/micro-rfc"
  color: "bfd4f2"
  description: "Micro-RFC proposal"

# COMPONENT
- name: "component/worker"
  color: "5319e7"
  description: "Cloudflare Worker"
- name: "component/do"
  color: "5319e7"
  description: "Durable Object"
- name: "component/cli"
  color: "5319e7"
  description: "tgk CLI"
- name: "component/iac"
  color: "5319e7"
  description: "alchemy.run.ts"
- name: "component/telegram"
  color: "5319e7"
  description: "Telegram integration"

# DEPT / TEAM
- name: "dept/infrastructure"
  color: "f9d0c4"
  description: "Infra & CI/CD"
- name: "dept/docs"
  color: "f9d0c4"
  description: "Documentation"
- name: "dept/security"
  color: "f9d0c4"
  description: "Security hardening"

# PRIORITY
- name: "priority/critical"
  color: "b60205"
  description: "Drop everything"
- name: "priority/high"
  color: "ff9f1c"
  description: "Next sprint"
- name: "priority/medium"
  color: "fffa65"
  description: "Normal queue"
- name: "priority/low"
  color: "2ea44f"
  description: "Nice to have"

# STATUS
- name: "status/blocked"
  color: "ffffff"
  description: "External dependency"
- name: "status/rfc-ready"
  color: "0e8a16"
  description: "RFC approved, needs code"
- name: "status/needs-review"
  color: "fffa65"
  description: "Awaiting core review"

# SIZE
- name: "size/xs"
  color: "c5def5"
  description: "< 10 LOC"
- name: "size/s"
  color: "c5def5"
  description: "10-50 LOC"
- name: "size/m"
  color: "c5def5"
  description: "50-200 LOC"
- name: "size/l"
  color: "c5def5"
  description: "200-500 LOC"
- name: "size/xl"
  color: "c5def5"
  description: "> 500 LOC"

# CUSTOMER GROUP
- name: "customer/group-alpha"
  color: "0366d6"
  description: "Alpha testers / early adopters"
- name: "customer/group-beta"
  color: "0366d6"
  description: "Beta users"
- name: "customer/enterprise"
  color: "0366d6"
  description: "Paid enterprise accounts"
- name: "customer/internal"
  color: "0366d6"
  description: "Dog-food / internal usage"

# CUSTOMER TOPIC
- name: "topic/telegram-group"
  color: "1d76db"
  description: "Telegram super-group feature"
- name: "topic/forum-topic"
  color: "1d76db"
  description: "Forum topic / thread"
- name: "topic/state-pinning"
  color: "1d76db"
  description: "Pinned message state"
- name: "topic/race-condition"
  color: "1d76db"
  description: "Concurrent update issues"

# CUSTOMER IMPACT
- name: "impact/critical"
  color: "b60205"
  description: "Customer blocked / revenue at risk"
- name: "impact/high"
  color: "ff9f1c"
  description: "Significant customer pain"
- name: "impact/low"
  color: "2ea44f"
  description: "Nice-to-have for customers"

# RELEASE TYPE
- name: "release/major"
  color: "d73a4a"
  description: "Breaking API change"
- name: "release/minor"
  color: "fbca04"
  description: "New feature (non-breaking)"
- name: "release/patch"
  color: "2ea44f"
  description: "Bug-fix (non-breaking)"

# RELEASE STATE
- name: "release/draft"
  color: "ffffff"
  description: "Pre-release"
- name: "release/candidate"
  color: "fffa65"
  description: "Release candidate"
- name: "release/stable"
  color: "0e8a16"
  description: "General availability"
