name: Auto Merge

on:
  pull_request_review:
    types: [submitted]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved' &&
      github.event.pull_request.draft == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd tgk
          npm install

      - name: Setup tgk CLI
        run: |
          cd tgk
          npm link

      - name: Check auto-merge eligibility
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Checking auto-merge for PR #$PR_NUMBER"

          # Check if PR has required labels
          REQUIRED_LABELS=("size/xs" "size/s" "dept/infrastructure" "dept/docs" "component/cli" "component/worker")
          HAS_REQUIRED_LABEL=false

          for label in "${REQUIRED_LABELS[@]}"; do
            if gh pr view $PR_NUMBER --json labels --jq ".labels[].name" | grep -q "^$label$"; then
              HAS_REQUIRED_LABEL=true
              echo "Found required label: $label"
              break
            fi
          done

          if [ "$HAS_REQUIRED_LABEL" = true ]; then
            echo "auto_merge=true" >> $GITHUB_OUTPUT
          else
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Enable auto-merge
        if: steps.check.outputs.auto_merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Enabling auto-merge for PR #$PR_NUMBER"

          tgk github pr automate $PR_NUMBER

      - name: Notify merge readiness
        if: steps.check.outputs.auto_merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_COUNCIL_ID: ${{ secrets.TELEGRAM_COUNCIL_ID }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE=$(gh pr view $PR_NUMBER --json title --jq .title)

          echo "🤖 Auto-merge enabled for PR #$PR_NUMBER: $PR_TITLE"
